[env:selector]
platform = espressif32
board = heltec_wifi_lora_32_V4
framework = arduino, espidf
board_build.partitions = partitions.csv
board_build.filesystem = spiffs

; Libraries
lib_deps =
    olikraus/U8g2@^2.35.19

; Serial monitor
monitor_speed = 115200

; Upload speed
upload_speed = 921600

; Build flags
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM
